### ISSUE TITLE
Class 'Carbon\Laravel\ServiceProvider' not found

### ISSUE THREAD

**Issue by madzat** [wicod/laravel-5-starter#1]
Hello,

I installed the package by composer and following the steps described in the documentation, but I can not copy the package configuration file for error account below:

In ProviderRepository.php line 208:
                                                    
  Class 'Carbon\Laravel\ServiceProvider' not found  
                                                    

Script php artisan clear-compiled handling the post-update-cmd event returned with error code 1

any help?

**Comment by wicod** [comment]
And it must be understood that it is a package that serves me to change things. There can be a lot of useless things ...
And that he is perpetual development.
Dig a little, you will find the problem.
Sorry,i'm not on it right now, I can not help you.

**Comment by madzat** [comment]
slt merci de votre réponse je veux tester ta version maix quand je faix la composer update je resoi cette error c ca mon problem 
> C:\ProgramData\ComposerSetup\bin\composer.bat update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 0 removals
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan clear-compiled

In ProviderRepository.php line 208:
                                                    
  Class 'Carbon\Laravel\ServiceProvider' not found  
                                                    

Script php artisan clear-compiled handling the post-update-cmd event returned with error code 1

Process finished with exit code 1 at 18:26:10.
Execution time: 18,957 ms.

**Comment by wicod** [comment]
Pas de langage SMS stp..

Déjà, mauvaise idée d'être sous Windows... ...Guète Linux Debian...
Ensuite as tu bien cloné tous les dossiers du projet car je n'ai pas fait d'installer par composer.
Suffit de tout cloner et "composer update" (voir à mettre à jour ton composer aussi)
Et PHP >= 7.1.3

**Comment by wicod** [comment]
Sinon, t'es familiarisé pas mal avec Laravel ?
Car c'est pas forcément tout cru après.. Mais si t'arrive à le démarrer tu vas voir qu'il y a du boulot de fait..

**Comment by wicod** [comment]
> C:\ProgramData\ComposerSetup\bin\composer.bat update

Déjà, j'ai l'impression que t'es pas logger dans le dossier du projet... A moins que t'es mis le projet dans C:\
Depuis ton IDE, ouvre une console à la racine du projet et lance la commande "composer update"

**Comment by wicod** [comment]
Je viens de le mettre à jour, no souci..
Attend je fait un push all et je te dirai quand tu pourras recommencer..

**Comment by wicod** [comment]
Là. Supprime tout, re-clone le nouveau et loge toi dans le dossier où tu la cloné pour faire la commande "composer update"
Si ça passe pas creuse car je vois pas (Windobe)
Bon courage.  ça vaut le coup..

**Comment by madzat** [comment]
merci je vais faire un essai maintenant et vous faire savoir

**Comment by wicod** [comment]
Ouais ce serait cool. Courage, Google est ton faux ami... mais ça marche quand même...

**Comment by wicod** [comment]
Normalement, le faire démarrer prend 5 minutes.. mais après il y a du taf quand même..
Et je le redis, il manquera (des fois) des dossiers, faudrat les créer manuellement. 
Genre pour y mettre les images ou vidéos téléchargées. Mais rien de bien méchant, suffit de regarder les erreurs qui sortent de la console ou autre..
Bonne soirée..

**Comment by madzat** [comment]
merci ca marche la et bonne soirée

**Comment by wicod** [comment]
Bonne découverte, car Laravel + VueJS........
Fait moi part de tes réactions si tu veux.
A+
